package tuwien.dbai.wpps.ontschema;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from dom.owl 
 * @author Auto-generated by schemagen on 04 Oct 2012 20:26 
 */
public class DOMOnt {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty ancestorOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#ancestorOf" );
    
    public static final ObjectProperty attributeOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#attributeOf" );
    
    public static final ObjectProperty childOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#childOf" );
    
    public static final ObjectProperty descendantOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#descendantOf" );
    
    public static final ObjectProperty firstChildOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#firstChildOf" );
    
    public static final ObjectProperty hasAttribute = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasAttribute" );
    
    public static final ObjectProperty hasAttributes = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasAttributes" );
    
    public static final ObjectProperty hasFirstChild = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasFirstChild" );
    
    public static final ObjectProperty hasLastChild = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasLastChild" );
    
    public static final ObjectProperty hasSibling = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasSibling" );
    
    public static final ObjectProperty justAfterSibling = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#justAfterSibling" );
    
    public static final ObjectProperty justBeforeSibling = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#justBeforeSibling" );
    
    public static final ObjectProperty lastChildOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#lastChildOf" );
    
    public static final ObjectProperty parentOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#parentOf" );
    
    /** <p>Incremental id which was gotten during depth-first search watch.</p> */
    public static final DatatypeProperty dfsId = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#dfsId" );
    
    public static final DatatypeProperty hasAttributeCodeEnabled = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasAttributeCodeEnabled" );
    
    /** <p>String with attributes in form (&lt;attribute_name&gt;="&lt;value&gt;" )+</p> */
    public static final DatatypeProperty hasAttributesCode = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasAttributesCode" );
    
    /** <p>String with attributes from computed CSS in form (&lt;attribute_name&gt;="&lt;value&gt;" 
     *  )+</p>
     */
    public static final DatatypeProperty hasComputedCssCode = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasComputedCssCode" );
    
    public static final DatatypeProperty hasComputedCssCodeEnabled = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasComputedCssCodeEnabled" );
    
    public static final DatatypeProperty hasCreatedAttributes = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasCreatedAttributes" );
    
    /** <p>Does not used yet.</p> */
    public static final DatatypeProperty hasCreatedCssAttributes = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasCreatedCssAttributes" );
    
    public static final DatatypeProperty hasNodeName = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasNodeName" );
    
    public static final DatatypeProperty hasNodeValue = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasNodeValue" );
    
    public static final DatatypeProperty hasNs = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasNs" );
    
    public static final DatatypeProperty hasPublicId = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasPublicId" );
    
    public static final DatatypeProperty hasSystemId = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasSystemId" );
    
    public static final DatatypeProperty hasXPath = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#hasXPath" );
    
    public static final DatatypeProperty treeLevelIndex = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#treeLevelIndex" );
    
    /** <p>DOM Attribute Node</p> */
    public static final OntClass Attribute = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Attribute" );
    
    public static final OntClass CDATASection = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#CDATASection" );
    
    public static final OntClass Comment = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Comment" );
    
    public static final OntClass Document = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Document" );
    
    public static final OntClass DocumentFragment = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#DocumentFragment" );
    
    public static final OntClass DocumentType = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#DocumentType" );
    
    /** <p>Node which has its type according the W3C classification for the nodes in 
     *  DOM Tree</p>
     */
    public static final OntClass DomNodeType = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#DomNodeType" );
    
    /** <p>DOM Element Node</p> */
    public static final OntClass Element = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Element" );
    
    public static final OntClass Entity = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Entity" );
    
    public static final OntClass EntityReference = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#EntityReference" );
    
    public static final OntClass LeafRestriction = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#LeafRestriction" );
    
    /** <p>Main element is a element which is important for visual representation. For 
     *  HTML code it is a BODY tag. For XML it is a root element.</p>
     */
    public static final OntClass MainElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#MainElement" );
    
    /** <p>Dom node.</p> */
    public static final OntClass Node = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Node" );
    
    public static final OntClass NonTraversalNode = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#NonTraversalNode" );
    
    public static final OntClass Notation = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Notation" );
    
    public static final OntClass ProcessingInstruction = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#ProcessingInstruction" );
    
    /** <p>Root node of the DOM Tree. It has such a restriction as there is no related 
     *  childOf or descendantOf relations.</p>
     */
    public static final OntClass Root = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Root" );
    
    /** <p>DOM Text Node</p> */
    public static final OntClass Text = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#Text" );
    
    public static final OntClass TraversalNode = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/dom#TraversalNode" );
    
}
