package tuwien.dbai.wpps.ontschema;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from interface-model.owl 
 * @author Auto-generated by schemagen on 03 Nov 2012 13:33 
 */
public class InterfaceModelOnt {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasAttribute = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasAttribute" );
    
    public static final ObjectProperty hasCheckBoxes = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasCheckBoxes" );
    
    public static final ObjectProperty hasFontFamilies = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasFontFamilies" );
    
    public static final ObjectProperty hasFontStyle = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasFontStyle" );
    
    public static final ObjectProperty hasHtmlElements = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasHtmlElements" );
    
    public static final ObjectProperty hasHtmlLink = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasHtmlLink" );
    
    public static final ObjectProperty hasListItems = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasListItems" );
    
    public static final ObjectProperty hasOptions = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasOptions" );
    
    public static final ObjectProperty hasRadioButtons = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasRadioButtons" );
    
    public static final ObjectProperty hasTableCells = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTableCells" );
    
    public static final ObjectProperty hasTableColumns = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTableColumns" );
    
    public static final ObjectProperty hasTableRows = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTableRows" );
    
    public static final ObjectProperty hasTextDecoration = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTextDecoration" );
    
    public static final ObjectProperty hasWPBIElements = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasWPBIElements" );
    
    public static final ObjectProperty hasWPBILink = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasWPBILink" );
    
    public static final ObjectProperty hasWebFormElements = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasWebFormElements" );
    
    public static final ObjectProperty hasWebFormMethod = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasWebFormMethod" );
    
    public static final ObjectProperty inHtmlButton = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#inHtmlButton" );
    
    public static final ObjectProperty isHtmlElementOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#isHtmlElementOf" );
    
    public static final ObjectProperty isWPBIElementOf = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#isWPBIElementOf" );
    
    /** <p>TODO: add into Java code</p> */
    public static final DatatypeProperty hasAccessKey = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasAccessKey" );
    
    /** <p>Action attribute of the web form.</p> */
    public static final DatatypeProperty hasAction = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasAction" );
    
    public static final DatatypeProperty hasAltText = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasAltText" );
    
    public static final DatatypeProperty hasFontFamily = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasFontFamily" );
    
    public static final DatatypeProperty hasFontSize = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasFontSize" );
    
    public static final DatatypeProperty hasFontWeight = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasFontWeight" );
    
    /** <p>add into java code?</p> */
    public static final DatatypeProperty hasTagName = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTagName" );
    
    public static final DatatypeProperty hasTextValue = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasTextValue" );
    
    public static final DatatypeProperty hasUri = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#hasUri" );
    
    public static final DatatypeProperty isChecked = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#isChecked" );
    
    public static final DatatypeProperty isHtmlInputButton = m_model.createDatatypeProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#isHtmlInputButton" );
    
    public static final OntClass Attribute = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Attribute" );
    
    public static final OntClass DescriptionList = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#DescriptionList" );
    
    public static final OntClass FontStyle = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#FontStyle" );
    
    public static final OntClass HtmlButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlButton" );
    
    public static final OntClass HtmlCheckBox = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlCheckBox" );
    
    public static final OntClass HtmlElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlElement" );
    
    public static final OntClass HtmlFileUpload = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlFileUpload" );
    
    public static final OntClass HtmlImage = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlImage" );
    
    public static final OntClass HtmlLink = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlLink" );
    
    public static final OntClass HtmlList = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlList" );
    
    public static final OntClass HtmlListItem = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlListItem" );
    
    public static final OntClass HtmlNormalButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlNormalButton" );
    
    public static final OntClass HtmlOption = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlOption" );
    
    public static final OntClass HtmlPasswordInput = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlPasswordInput" );
    
    public static final OntClass HtmlRadioButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlRadioButton" );
    
    public static final OntClass HtmlResetButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlResetButton" );
    
    public static final OntClass HtmlSelect = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlSelect" );
    
    public static final OntClass HtmlSubmitButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlSubmitButton" );
    
    public static final OntClass HtmlTable = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlTable" );
    
    public static final OntClass HtmlTableCell = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlTableCell" );
    
    public static final OntClass HtmlTableRow = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlTableRow" );
    
    public static final OntClass HtmlText = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlText" );
    
    public static final OntClass HtmlTextArea = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlTextArea" );
    
    public static final OntClass HtmlTextInput = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlTextInput" );
    
    public static final OntClass HtmlWebForm = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlWebForm" );
    
    public static final OntClass HtmlWebFormElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#HtmlWebFormElement" );
    
    public static final OntClass LeafElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#LeafElement" );
    
    public static final OntClass ListType = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#ListType" );
    
    public static final OntClass OrderedList = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#OrderedList" );
    
    public static final OntClass TextDecoration = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#TextDecoration" );
    
    public static final OntClass UnorderedList = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#UnorderedList" );
    
    public static final OntClass VisibleElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#VisibleElement" );
    
    public static final OntClass WPBICheckBox = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBICheckBox" );
    
    /** <p>Check Box Group which group different chackboces with the same name.</p> */
    public static final OntClass WPBICheckBoxGroup = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBICheckBoxGroup" );
    
    public static final OntClass WPBIElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIElement" );
    
    public static final OntClass WPBILink = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBILink" );
    
    public static final OntClass WPBIList = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIList" );
    
    public static final OntClass WPBIListItem = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIListItem" );
    
    public static final OntClass WPBIRadioButton = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIRadioButton" );
    
    /** <p>Check Box Group which group different chackboces with the same name.</p> */
    public static final OntClass WPBIRadioButtonGroup = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIRadioButtonGroup" );
    
    public static final OntClass WPBITable = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBITable" );
    
    public static final OntClass WPBITableCell = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBITableCell" );
    
    public static final OntClass WPBITableColumn = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBITableColumn" );
    
    public static final OntClass WPBITableRow = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBITableRow" );
    
    public static final OntClass WPBIText = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WPBIText" );
    
    public static final OntClass WebFormMethod = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#WebFormMethod" );
    
    public static final OntClass XmlElement = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#XmlElement" );
    
    public static final Individual Blink = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Blink", TextDecoration );
    
    public static final Individual Get = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Get", WebFormMethod );
    
    public static final Individual Italic = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Italic", FontStyle );
    
    public static final Individual LineThrough = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#LineThrough", TextDecoration );
    
    public static final Individual NoTextDecoration = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#NoTextDecoration", TextDecoration );
    
    public static final Individual NormalFontStyle = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#NormalFontStyle", FontStyle );
    
    public static final Individual Oblique = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Oblique", FontStyle );
    
    public static final Individual Overline = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Overline", TextDecoration );
    
    public static final Individual Post = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Post", WebFormMethod );
    
    public static final Individual Underline = m_model.createIndividual( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/interface-model#Underline", TextDecoration );
    
}
