package tuwien.dbai.wpps.ontschema;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from result.owl 
 * @author Auto-generated by schemagen on 23 Sep 2012 21:35 
 */
public class ResultOnt {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasFirstResult = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#hasFirstResult" );
    
    public static final ObjectProperty hasLastResult = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#hasLastResult" );
    
    public static final ObjectProperty hasResult = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#hasResult" );
    
    public static final ObjectProperty hasResults = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#hasResults" );
    
    public static final ObjectProperty inResultsContainer = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#inResultsContainer" );
    
    public static final ObjectProperty nextResult = m_model.createObjectProperty( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#nextResult" );
    
    public static final OntClass ResultsContainer = m_model.createClass( "http://www.dbai.tuwien.ac.at/proj/wpps/ontologies/result#ResultsContainer" );
    
}
